// AUTO-GENERATED by the high-resolution asset import. Do not edit by hand.
// Source artwork: 1120x1280 PNG / MP4 (Higher resolution/), rendered on the
// 280x320 design grid (Lanczos downscale on device).

import a_exercise_breathing_exercises_png from "@/assets/tft/hi/exercise_breathing_exercises.png.asset.json";
import a_exercise_mindfulness_meditation_png from "@/assets/tft/hi/exercise_mindfulness_meditation.png.asset.json";
import a_exercise_positive_thinking_emotional_wellness_png from "@/assets/tft/hi/exercise_positive_thinking_emotional_wellness.png.asset.json";
import a_exercise_random_exercise_png from "@/assets/tft/hi/exercise_random_exercise.png.asset.json";
import a_exercise_sleep_recovery_png from "@/assets/tft/hi/exercise_sleep_recovery.png.asset.json";
import a_exercise_stress_anxiety_relief_png from "@/assets/tft/hi/exercise_stress_anxiety_relief.png.asset.json";
import a_home_page_nowifi_mobile_auto_bat1_png from "@/assets/tft/hi/home_page_nowifi_mobile_auto_bat1.png.asset.json";
import a_home_page_nowifi_mobile_auto_bat2_png from "@/assets/tft/hi/home_page_nowifi_mobile_auto_bat2.png.asset.json";
import a_home_page_nowifi_mobile_auto_bat3_png from "@/assets/tft/hi/home_page_nowifi_mobile_auto_bat3.png.asset.json";
import a_home_page_nowifi_mobile_auto_bat4_png from "@/assets/tft/hi/home_page_nowifi_mobile_auto_bat4.png.asset.json";
import a_home_page_nowifi_mobile_auto_batempty_png from "@/assets/tft/hi/home_page_nowifi_mobile_auto_batempty.png.asset.json";
import a_home_page_nowifi_mobile_cloud_bat1_png from "@/assets/tft/hi/home_page_nowifi_mobile_cloud_bat1.png.asset.json";
import a_home_page_nowifi_mobile_cloud_bat2_png from "@/assets/tft/hi/home_page_nowifi_mobile_cloud_bat2.png.asset.json";
import a_home_page_nowifi_mobile_cloud_bat3_png from "@/assets/tft/hi/home_page_nowifi_mobile_cloud_bat3.png.asset.json";
import a_home_page_nowifi_mobile_cloud_bat4_png from "@/assets/tft/hi/home_page_nowifi_mobile_cloud_bat4.png.asset.json";
import a_home_page_nowifi_mobile_cloud_batempty_png from "@/assets/tft/hi/home_page_nowifi_mobile_cloud_batempty.png.asset.json";
import a_home_page_nowifi_mobile_local_bat1_png from "@/assets/tft/hi/home_page_nowifi_mobile_local_bat1.png.asset.json";
import a_home_page_nowifi_mobile_local_bat2_png from "@/assets/tft/hi/home_page_nowifi_mobile_local_bat2.png.asset.json";
import a_home_page_nowifi_mobile_local_bat3_png from "@/assets/tft/hi/home_page_nowifi_mobile_local_bat3.png.asset.json";
import a_home_page_nowifi_mobile_local_bat4_png from "@/assets/tft/hi/home_page_nowifi_mobile_local_bat4.png.asset.json";
import a_home_page_nowifi_mobile_local_batempty_png from "@/assets/tft/hi/home_page_nowifi_mobile_local_batempty.png.asset.json";
import a_home_page_nowifi_nomobile_auto_bat1_png from "@/assets/tft/hi/home_page_nowifi_nomobile_auto_bat1.png.asset.json";
import a_home_page_nowifi_nomobile_auto_bat2_png from "@/assets/tft/hi/home_page_nowifi_nomobile_auto_bat2.png.asset.json";
import a_home_page_nowifi_nomobile_auto_bat3_png from "@/assets/tft/hi/home_page_nowifi_nomobile_auto_bat3.png.asset.json";
import a_home_page_nowifi_nomobile_auto_bat4_png from "@/assets/tft/hi/home_page_nowifi_nomobile_auto_bat4.png.asset.json";
import a_home_page_nowifi_nomobile_auto_batempty_png from "@/assets/tft/hi/home_page_nowifi_nomobile_auto_batempty.png.asset.json";
import a_home_page_nowifi_nomobile_cloud_bat2_png from "@/assets/tft/hi/home_page_nowifi_nomobile_cloud_bat2.png.asset.json";
import a_home_page_nowifi_nomobile_cloud_bat3_png from "@/assets/tft/hi/home_page_nowifi_nomobile_cloud_bat3.png.asset.json";
import a_home_page_nowifi_nomobile_cloud_bat4_png from "@/assets/tft/hi/home_page_nowifi_nomobile_cloud_bat4.png.asset.json";
import a_home_page_nowifi_nomobile_cloud_batempty_png from "@/assets/tft/hi/home_page_nowifi_nomobile_cloud_batempty.png.asset.json";
import a_home_page_nowifi_nomobile_local_bat1_png from "@/assets/tft/hi/home_page_nowifi_nomobile_local_bat1.png.asset.json";
import a_home_page_nowifi_nomobile_local_bat2_png from "@/assets/tft/hi/home_page_nowifi_nomobile_local_bat2.png.asset.json";
import a_home_page_nowifi_nomobile_local_bat3_png from "@/assets/tft/hi/home_page_nowifi_nomobile_local_bat3.png.asset.json";
import a_home_page_nowifi_nomobile_local_bat4_png from "@/assets/tft/hi/home_page_nowifi_nomobile_local_bat4.png.asset.json";
import a_home_page_splash_mp4 from "@/assets/tft/hi/home_page_splash.mp4.asset.json";
import a_home_page_wifi_mobile_auto_bat1_png from "@/assets/tft/hi/home_page_wifi_mobile_auto_bat1.png.asset.json";
import a_home_page_wifi_mobile_auto_bat2_png from "@/assets/tft/hi/home_page_wifi_mobile_auto_bat2.png.asset.json";
import a_home_page_wifi_mobile_auto_bat3_png from "@/assets/tft/hi/home_page_wifi_mobile_auto_bat3.png.asset.json";
import a_home_page_wifi_mobile_auto_bat4_png from "@/assets/tft/hi/home_page_wifi_mobile_auto_bat4.png.asset.json";
import a_home_page_wifi_mobile_auto_batempty_png from "@/assets/tft/hi/home_page_wifi_mobile_auto_batempty.png.asset.json";
import a_home_page_wifi_mobile_cloud_bat1_png from "@/assets/tft/hi/home_page_wifi_mobile_cloud_bat1.png.asset.json";
import a_home_page_wifi_mobile_cloud_bat2_png from "@/assets/tft/hi/home_page_wifi_mobile_cloud_bat2.png.asset.json";
import a_home_page_wifi_mobile_cloud_bat3_png from "@/assets/tft/hi/home_page_wifi_mobile_cloud_bat3.png.asset.json";
import a_home_page_wifi_mobile_cloud_bat4_png from "@/assets/tft/hi/home_page_wifi_mobile_cloud_bat4.png.asset.json";
import a_home_page_wifi_mobile_cloud_batempty_png from "@/assets/tft/hi/home_page_wifi_mobile_cloud_batempty.png.asset.json";
import a_home_page_wifi_mobile_local_bat1_png from "@/assets/tft/hi/home_page_wifi_mobile_local_bat1.png.asset.json";
import a_home_page_wifi_mobile_local_bat2_png from "@/assets/tft/hi/home_page_wifi_mobile_local_bat2.png.asset.json";
import a_home_page_wifi_mobile_local_bat3_png from "@/assets/tft/hi/home_page_wifi_mobile_local_bat3.png.asset.json";
import a_home_page_wifi_mobile_local_bat4_png from "@/assets/tft/hi/home_page_wifi_mobile_local_bat4.png.asset.json";
import a_home_page_wifi_mobile_local_batempty_png from "@/assets/tft/hi/home_page_wifi_mobile_local_batempty.png.asset.json";
import a_home_page_wifi_nomobile_auto_bat1_png from "@/assets/tft/hi/home_page_wifi_nomobile_auto_bat1.png.asset.json";
import a_home_page_wifi_nomobile_auto_bat2_png from "@/assets/tft/hi/home_page_wifi_nomobile_auto_bat2.png.asset.json";
import a_home_page_wifi_nomobile_auto_bat3_png from "@/assets/tft/hi/home_page_wifi_nomobile_auto_bat3.png.asset.json";
import a_home_page_wifi_nomobile_auto_bat4_png from "@/assets/tft/hi/home_page_wifi_nomobile_auto_bat4.png.asset.json";
import a_home_page_wifi_nomobile_auto_batempty_png from "@/assets/tft/hi/home_page_wifi_nomobile_auto_batempty.png.asset.json";
import a_home_page_wifi_nomobile_cloud_bat1_png from "@/assets/tft/hi/home_page_wifi_nomobile_cloud_bat1.png.asset.json";
import a_home_page_wifi_nomobile_cloud_bat2_png from "@/assets/tft/hi/home_page_wifi_nomobile_cloud_bat2.png.asset.json";
import a_home_page_wifi_nomobile_cloud_bat3_png from "@/assets/tft/hi/home_page_wifi_nomobile_cloud_bat3.png.asset.json";
import a_home_page_wifi_nomobile_cloud_bat4_png from "@/assets/tft/hi/home_page_wifi_nomobile_cloud_bat4.png.asset.json";
import a_home_page_wifi_nomobile_cloud_batempty_png from "@/assets/tft/hi/home_page_wifi_nomobile_cloud_batempty.png.asset.json";
import a_home_page_wifi_nomobile_local_bat1_png from "@/assets/tft/hi/home_page_wifi_nomobile_local_bat1.png.asset.json";
import a_home_page_wifi_nomobile_local_bat2_png from "@/assets/tft/hi/home_page_wifi_nomobile_local_bat2.png.asset.json";
import a_home_page_wifi_nomobile_local_bat3_png from "@/assets/tft/hi/home_page_wifi_nomobile_local_bat3.png.asset.json";
import a_home_page_wifi_nomobile_local_bat4_png from "@/assets/tft/hi/home_page_wifi_nomobile_local_bat4.png.asset.json";
import a_home_page_wifi_nomobile_local_batempty_png from "@/assets/tft/hi/home_page_wifi_nomobile_local_batempty.png.asset.json";
import a_mode_selection_adhd_png from "@/assets/tft/hi/mode_selection_adhd.png.asset.json";
import a_mode_selection_anxiety_png from "@/assets/tft/hi/mode_selection_anxiety.png.asset.json";
import a_mode_selection_bipolar_png from "@/assets/tft/hi/mode_selection_bipolar.png.asset.json";
import a_mode_selection_depression_png from "@/assets/tft/hi/mode_selection_depression.png.asset.json";
import a_mode_selection_mode_png from "@/assets/tft/hi/mode_selection_mode.png.asset.json";
import a_mode_selection_ptsd_png from "@/assets/tft/hi/mode_selection_ptsd.png.asset.json";
import a_mode_selection_schizo_png from "@/assets/tft/hi/mode_selection_schizo.png.asset.json";
import a_mood_angry_png from "@/assets/tft/hi/mood_angry.png.asset.json";
import a_mood_good_png from "@/assets/tft/hi/mood_good.png.asset.json";
import a_mood_great_png from "@/assets/tft/hi/mood_great.png.asset.json";
import a_mood_low_png from "@/assets/tft/hi/mood_low.png.asset.json";
import a_mood_mood_png from "@/assets/tft/hi/mood_mood.png.asset.json";
import a_mood_okay_png from "@/assets/tft/hi/mood_okay.png.asset.json";
import a_mood_sad_png from "@/assets/tft/hi/mood_sad.png.asset.json";
import a_other_pages_ai_response_animation_mp4 from "@/assets/tft/hi/other_pages_ai_response_animation.mp4.asset.json";
import a_other_pages_ai_response_animation_png from "@/assets/tft/hi/other_pages_ai_response_animation.png.asset.json";
import a_other_pages_call_connected_end_call_page_png from "@/assets/tft/hi/other_pages_call_connected_end_call_page.png.asset.json";
import a_other_pages_call_receive_page_png from "@/assets/tft/hi/other_pages_call_receive_page.png.asset.json";
import a_other_pages_calling_png from "@/assets/tft/hi/other_pages_calling.png.asset.json";
import a_other_pages_home_page_model_png from "@/assets/tft/hi/other_pages_home_page_model.png.asset.json";
import a_other_pages_keypad_png from "@/assets/tft/hi/other_pages_keypad.png.asset.json";
import a_other_pages_music_is_paused_mp4 from "@/assets/tft/hi/other_pages_music_is_paused.mp4.asset.json";
import a_other_pages_music_is_playing_mp4 from "@/assets/tft/hi/other_pages_music_is_playing.mp4.asset.json";
import a_settings_page_cloud_pipeline_png from "@/assets/tft/hi/settings_page_cloud_pipeline.png.asset.json";
import a_settings_page_device_config_png from "@/assets/tft/hi/settings_page_device_config.png.asset.json";
import a_settings_page_dnd_activated_png from "@/assets/tft/hi/settings_page_dnd_activated.png.asset.json";
import a_settings_page_dnd_deactivated_png from "@/assets/tft/hi/settings_page_dnd_deactivated.png.asset.json";
import a_settings_page_hybrid_pipeline_png from "@/assets/tft/hi/settings_page_hybrid_pipeline.png.asset.json";
import a_settings_page_local_pipeline_png from "@/assets/tft/hi/settings_page_local_pipeline.png.asset.json";
import a_settings_page_settings_png from "@/assets/tft/hi/settings_page_settings.png.asset.json";
import a_settings_page_voice_setting_adam_voice_png from "@/assets/tft/hi/settings_page_voice_setting_adam_voice.png.asset.json";
import a_settings_page_voice_setting_bella_voice_png from "@/assets/tft/hi/settings_page_voice_setting_bella_voice.png.asset.json";
import a_settings_page_voice_setting_default_voice_png from "@/assets/tft/hi/settings_page_voice_setting_default_voice.png.asset.json";
import a_settings_page_voice_setting_emma_voice_png from "@/assets/tft/hi/settings_page_voice_setting_emma_voice.png.asset.json";
import a_settings_page_voice_setting_michael_voice_png from "@/assets/tft/hi/settings_page_voice_setting_michael_voice.png.asset.json";
import a_settings_page_voice_setting_nicole_voice_png from "@/assets/tft/hi/settings_page_voice_setting_nicole_voice.png.asset.json";
import a_settings_page_voice_setting_sarah_voice_png from "@/assets/tft/hi/settings_page_voice_setting_sarah_voice.png.asset.json";
import a_settings_page_voice_setting_sky_voice_png from "@/assets/tft/hi/settings_page_voice_setting_sky_voice.png.asset.json";
import a_settings_page_wifi_page_png from "@/assets/tft/hi/settings_page_wifi_page.png.asset.json";

export const HIRES: Record<string, string> = {
  "exercise_breathing_exercises.png": a_exercise_breathing_exercises_png.url,
  "exercise_mindfulness_meditation.png": a_exercise_mindfulness_meditation_png.url,
  "exercise_positive_thinking_emotional_wellness.png": a_exercise_positive_thinking_emotional_wellness_png.url,
  "exercise_random_exercise.png": a_exercise_random_exercise_png.url,
  "exercise_sleep_recovery.png": a_exercise_sleep_recovery_png.url,
  "exercise_stress_anxiety_relief.png": a_exercise_stress_anxiety_relief_png.url,
  "home_page_nowifi_mobile_auto_bat1.png": a_home_page_nowifi_mobile_auto_bat1_png.url,
  "home_page_nowifi_mobile_auto_bat2.png": a_home_page_nowifi_mobile_auto_bat2_png.url,
  "home_page_nowifi_mobile_auto_bat3.png": a_home_page_nowifi_mobile_auto_bat3_png.url,
  "home_page_nowifi_mobile_auto_bat4.png": a_home_page_nowifi_mobile_auto_bat4_png.url,
  "home_page_nowifi_mobile_auto_batempty.png": a_home_page_nowifi_mobile_auto_batempty_png.url,
  "home_page_nowifi_mobile_cloud_bat1.png": a_home_page_nowifi_mobile_cloud_bat1_png.url,
  "home_page_nowifi_mobile_cloud_bat2.png": a_home_page_nowifi_mobile_cloud_bat2_png.url,
  "home_page_nowifi_mobile_cloud_bat3.png": a_home_page_nowifi_mobile_cloud_bat3_png.url,
  "home_page_nowifi_mobile_cloud_bat4.png": a_home_page_nowifi_mobile_cloud_bat4_png.url,
  "home_page_nowifi_mobile_cloud_batempty.png": a_home_page_nowifi_mobile_cloud_batempty_png.url,
  "home_page_nowifi_mobile_local_bat1.png": a_home_page_nowifi_mobile_local_bat1_png.url,
  "home_page_nowifi_mobile_local_bat2.png": a_home_page_nowifi_mobile_local_bat2_png.url,
  "home_page_nowifi_mobile_local_bat3.png": a_home_page_nowifi_mobile_local_bat3_png.url,
  "home_page_nowifi_mobile_local_bat4.png": a_home_page_nowifi_mobile_local_bat4_png.url,
  "home_page_nowifi_mobile_local_batempty.png": a_home_page_nowifi_mobile_local_batempty_png.url,
  "home_page_nowifi_nomobile_auto_bat1.png": a_home_page_nowifi_nomobile_auto_bat1_png.url,
  "home_page_nowifi_nomobile_auto_bat2.png": a_home_page_nowifi_nomobile_auto_bat2_png.url,
  "home_page_nowifi_nomobile_auto_bat3.png": a_home_page_nowifi_nomobile_auto_bat3_png.url,
  "home_page_nowifi_nomobile_auto_bat4.png": a_home_page_nowifi_nomobile_auto_bat4_png.url,
  "home_page_nowifi_nomobile_auto_batempty.png": a_home_page_nowifi_nomobile_auto_batempty_png.url,
  "home_page_nowifi_nomobile_cloud_bat2.png": a_home_page_nowifi_nomobile_cloud_bat2_png.url,
  "home_page_nowifi_nomobile_cloud_bat3.png": a_home_page_nowifi_nomobile_cloud_bat3_png.url,
  "home_page_nowifi_nomobile_cloud_bat4.png": a_home_page_nowifi_nomobile_cloud_bat4_png.url,
  "home_page_nowifi_nomobile_cloud_batempty.png": a_home_page_nowifi_nomobile_cloud_batempty_png.url,
  "home_page_nowifi_nomobile_local_bat1.png": a_home_page_nowifi_nomobile_local_bat1_png.url,
  "home_page_nowifi_nomobile_local_bat2.png": a_home_page_nowifi_nomobile_local_bat2_png.url,
  "home_page_nowifi_nomobile_local_bat3.png": a_home_page_nowifi_nomobile_local_bat3_png.url,
  "home_page_nowifi_nomobile_local_bat4.png": a_home_page_nowifi_nomobile_local_bat4_png.url,
  "home_page_splash.mp4": a_home_page_splash_mp4.url,
  "home_page_wifi_mobile_auto_bat1.png": a_home_page_wifi_mobile_auto_bat1_png.url,
  "home_page_wifi_mobile_auto_bat2.png": a_home_page_wifi_mobile_auto_bat2_png.url,
  "home_page_wifi_mobile_auto_bat3.png": a_home_page_wifi_mobile_auto_bat3_png.url,
  "home_page_wifi_mobile_auto_bat4.png": a_home_page_wifi_mobile_auto_bat4_png.url,
  "home_page_wifi_mobile_auto_batempty.png": a_home_page_wifi_mobile_auto_batempty_png.url,
  "home_page_wifi_mobile_cloud_bat1.png": a_home_page_wifi_mobile_cloud_bat1_png.url,
  "home_page_wifi_mobile_cloud_bat2.png": a_home_page_wifi_mobile_cloud_bat2_png.url,
  "home_page_wifi_mobile_cloud_bat3.png": a_home_page_wifi_mobile_cloud_bat3_png.url,
  "home_page_wifi_mobile_cloud_bat4.png": a_home_page_wifi_mobile_cloud_bat4_png.url,
  "home_page_wifi_mobile_cloud_batempty.png": a_home_page_wifi_mobile_cloud_batempty_png.url,
  "home_page_wifi_mobile_local_bat1.png": a_home_page_wifi_mobile_local_bat1_png.url,
  "home_page_wifi_mobile_local_bat2.png": a_home_page_wifi_mobile_local_bat2_png.url,
  "home_page_wifi_mobile_local_bat3.png": a_home_page_wifi_mobile_local_bat3_png.url,
  "home_page_wifi_mobile_local_bat4.png": a_home_page_wifi_mobile_local_bat4_png.url,
  "home_page_wifi_mobile_local_batempty.png": a_home_page_wifi_mobile_local_batempty_png.url,
  "home_page_wifi_nomobile_auto_bat1.png": a_home_page_wifi_nomobile_auto_bat1_png.url,
  "home_page_wifi_nomobile_auto_bat2.png": a_home_page_wifi_nomobile_auto_bat2_png.url,
  "home_page_wifi_nomobile_auto_bat3.png": a_home_page_wifi_nomobile_auto_bat3_png.url,
  "home_page_wifi_nomobile_auto_bat4.png": a_home_page_wifi_nomobile_auto_bat4_png.url,
  "home_page_wifi_nomobile_auto_batempty.png": a_home_page_wifi_nomobile_auto_batempty_png.url,
  "home_page_wifi_nomobile_cloud_bat1.png": a_home_page_wifi_nomobile_cloud_bat1_png.url,
  "home_page_wifi_nomobile_cloud_bat2.png": a_home_page_wifi_nomobile_cloud_bat2_png.url,
  "home_page_wifi_nomobile_cloud_bat3.png": a_home_page_wifi_nomobile_cloud_bat3_png.url,
  "home_page_wifi_nomobile_cloud_bat4.png": a_home_page_wifi_nomobile_cloud_bat4_png.url,
  "home_page_wifi_nomobile_cloud_batempty.png": a_home_page_wifi_nomobile_cloud_batempty_png.url,
  "home_page_wifi_nomobile_local_bat1.png": a_home_page_wifi_nomobile_local_bat1_png.url,
  "home_page_wifi_nomobile_local_bat2.png": a_home_page_wifi_nomobile_local_bat2_png.url,
  "home_page_wifi_nomobile_local_bat3.png": a_home_page_wifi_nomobile_local_bat3_png.url,
  "home_page_wifi_nomobile_local_bat4.png": a_home_page_wifi_nomobile_local_bat4_png.url,
  "home_page_wifi_nomobile_local_batempty.png": a_home_page_wifi_nomobile_local_batempty_png.url,
  "mode_selection_adhd.png": a_mode_selection_adhd_png.url,
  "mode_selection_anxiety.png": a_mode_selection_anxiety_png.url,
  "mode_selection_bipolar.png": a_mode_selection_bipolar_png.url,
  "mode_selection_depression.png": a_mode_selection_depression_png.url,
  "mode_selection_mode.png": a_mode_selection_mode_png.url,
  "mode_selection_ptsd.png": a_mode_selection_ptsd_png.url,
  "mode_selection_schizo.png": a_mode_selection_schizo_png.url,
  "mood_angry.png": a_mood_angry_png.url,
  "mood_good.png": a_mood_good_png.url,
  "mood_great.png": a_mood_great_png.url,
  "mood_low.png": a_mood_low_png.url,
  "mood_mood.png": a_mood_mood_png.url,
  "mood_okay.png": a_mood_okay_png.url,
  "mood_sad.png": a_mood_sad_png.url,
  "other_pages_ai_response_animation.mp4": a_other_pages_ai_response_animation_mp4.url,
  "other_pages_ai_response_animation.png": a_other_pages_ai_response_animation_png.url,
  "other_pages_call_connected_end_call_page.png": a_other_pages_call_connected_end_call_page_png.url,
  "other_pages_call_receive_page.png": a_other_pages_call_receive_page_png.url,
  "other_pages_calling.png": a_other_pages_calling_png.url,
  "other_pages_home_page_model.png": a_other_pages_home_page_model_png.url,
  "other_pages_keypad.png": a_other_pages_keypad_png.url,
  "other_pages_music_is_paused.mp4": a_other_pages_music_is_paused_mp4.url,
  "other_pages_music_is_playing.mp4": a_other_pages_music_is_playing_mp4.url,
  "settings_page_cloud_pipeline.png": a_settings_page_cloud_pipeline_png.url,
  "settings_page_device_config.png": a_settings_page_device_config_png.url,
  "settings_page_dnd_activated.png": a_settings_page_dnd_activated_png.url,
  "settings_page_dnd_deactivated.png": a_settings_page_dnd_deactivated_png.url,
  "settings_page_hybrid_pipeline.png": a_settings_page_hybrid_pipeline_png.url,
  "settings_page_local_pipeline.png": a_settings_page_local_pipeline_png.url,
  "settings_page_settings.png": a_settings_page_settings_png.url,
  "settings_page_voice_setting_adam_voice.png": a_settings_page_voice_setting_adam_voice_png.url,
  "settings_page_voice_setting_bella_voice.png": a_settings_page_voice_setting_bella_voice_png.url,
  "settings_page_voice_setting_default_voice.png": a_settings_page_voice_setting_default_voice_png.url,
  "settings_page_voice_setting_emma_voice.png": a_settings_page_voice_setting_emma_voice_png.url,
  "settings_page_voice_setting_michael_voice.png": a_settings_page_voice_setting_michael_voice_png.url,
  "settings_page_voice_setting_nicole_voice.png": a_settings_page_voice_setting_nicole_voice_png.url,
  "settings_page_voice_setting_sarah_voice.png": a_settings_page_voice_setting_sarah_voice_png.url,
  "settings_page_voice_setting_sky_voice.png": a_settings_page_voice_setting_sky_voice_png.url,
  "settings_page_wifi_page.png": a_settings_page_wifi_page_png.url,
};
