from pathlib import Path

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
PIO_ENV = env.subst("$PIOENV")

TFT_ESPI_SETUP = PROJECT_DIR / ".pio" / "libdeps" / PIO_ENV / "TFT_eSPI" / "User_Setup.h"

USER_SETUP = r"""// MindBuddy ESP32 DevKit TFT_eSPI setup
// This file is generated by firmware/esp32-devmodule/scripts/patch_tft_espi_setup.py
// It is written directly into .pio/libdeps/esp32dev/TFT_eSPI/User_Setup.h.

#pragma once

#define USER_SETUP_INFO "MindBuddy ESP32 DevKit ILI9341 + XPT2046"

// 2.8 inch ILI9341 TFT panel on the ESP32 VSPI bus.
#define ILI9341_DRIVER

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18

// Safe non-strapping control pins from the README wiring table.
#define TFT_CS   32
#define TFT_DC   22
#define TFT_RST  21
#define TFT_BL   26
#define TFT_BACKLIGHT_ON HIGH

// XPT2046 touch controller, sharing the same VSPI bus.
#define TOUCH_CS 33

#define SPI_FREQUENCY       27000000
#define SPI_READ_FREQUENCY  20000000
#define SPI_TOUCH_FREQUENCY 2500000

#define LOAD_GLCD
#define LOAD_FONT2
#define LOAD_FONT4
#define LOAD_FONT6
#define LOAD_FONT7
#define LOAD_FONT8
#define LOAD_GFXFF
#define SMOOTH_FONT
"""


def patch_tft_espi_setup(*_args, **_kwargs):
    if not TFT_ESPI_SETUP.parent.exists():
        print(f"[tft] TFT_eSPI library folder not found yet: {TFT_ESPI_SETUP.parent}")
        return

    current = TFT_ESPI_SETUP.read_text(encoding="utf-8", errors="ignore") if TFT_ESPI_SETUP.exists() else ""
    if current == USER_SETUP:
        print(f"[tft] TFT_eSPI User_Setup.h already patched: {TFT_ESPI_SETUP}")
        return

    TFT_ESPI_SETUP.write_text(USER_SETUP, encoding="utf-8")
    print(f"[tft] patched TFT_eSPI User_Setup.h: {TFT_ESPI_SETUP}")


patch_tft_espi_setup()
env.AddPreAction("buildprog", patch_tft_espi_setup)